#!/usr/bin/env bash

# Script that runs all unit tests.

action() {
    local this_file="$( [ ! -z "$ZSH_VERSION" ] && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "$this_file" )" && pwd )"
    local ap_dir="$( dirname "$this_dir" )"

    # dev flag for sandboxes
    local dev="$( $AP_DEV && echo "_dev" || echo "" )"

    # start tests and keep track of immediate and global return values
    local gret="0"
    local ret

    # test_util
    bash "${this_dir}/run_test" test_util
    ret="$?"
    [ "$gret" = "0" ] && gret="$ret"

    # test_columnar_util
    echo
    bash "${this_dir}/run_test" test_columnar_util "venv_columnar${dev}.sh"
    ret="$?"
    [ "$gret" = "0" ] && gret="$ret"

    return "$gret"
}
action "$@"
