#!/usr/bin/env bash

# Script that builds and checks the documentation.
#
# Arguments:
#   1. The mode. When "clean", previously created docs are removed first. No default.

action() {
    local shell_is_zsh=$( [ -z "${ZSH_VERSION}" ] && echo "false" || echo "true" )
    local this_file="$( ${shell_is_zsh} && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "${this_file}" )" && pwd )"
    local cf_dir="$( dirname "$this_dir" )"

    # get arguments
    local mode=${1}

    # clean first if requested
    if [ "$mode" = "clean" ]; then
        ( cd "$cf_dir/docs" && make clean ) || return "$?"
    fi

    # build
    (
        source "$cf_dir/sandboxes/venv_docs_dev.sh" "" && \
        cd "$cf_dir/docs" && \
        make html
    ) || return "$?"
}
action "$@"
