#!/usr/bin/env bash

# Script that runs linting checks on selected files.

action() {
    local this_file="$( [ ! -z "$ZSH_VERSION" ] && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "$this_file" )" && pwd )"
    local cf_dir="$( dirname "$this_dir" )"

    (
        cd "$cf_dir" && \
        flake8 columnflow tests docs
    )
}
action "$@"
