#!/usr/bin/env bash

# Script that runs coverage tests.

action() {
    local this_file="$( [ ! -z "$ZSH_VERSION" ] && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "$this_file" )" && pwd )"
    local ap_dir="$( dirname "$this_dir" )"
    local test_base="$( basename "$this_dir" )"

    (
        cd "$ap_dir" && \
        pytest --cov=ap --cov-report xml:coverage.xml "$test_base"
    )
}
action "$@"
