#!/usr/bin/env bash

# Script that builds and checks the documentation.
#
# Arguments:
#   1. The mode. When "clean", previously created docs are removed first. No default.


action() {
    local this_file="$( [ ! -z "$ZSH_VERSION" ] && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "$this_file" )" && pwd )"
    local ap_dir="$( dirname "$this_dir" )"

    # get arguments
    local mode=${1}

    # clean first if requested
    if [ "$mode" = "clean" ]; then
        ( cd "$ap_dir/docs" && make clean ) || return "$?"
    fi

    # build
    (
        source "$ap_dir/sandboxes/venv_docs_dev.sh" "" && \
        cd "$ap_dir/docs" && \
        make html
    )
}
action "$@"
