#!/usr/bin/env bash

# Script that runs all unit tests.

action() {
    local shell_is_zsh=$( [ -z "${ZSH_VERSION}" ] && echo "false" || echo "true" )
    local this_file="$( ${shell_is_zsh} && echo "${(%):-%x}" || echo "${BASH_SOURCE[0]}" )"
    local this_dir="$( cd "$( dirname "${this_file}" )" && pwd )"
    local cf_dir="$( dirname "${this_dir}" )"

    # dev flag for sandboxes
    local dev="$( [ "${CF_DEV}" = "1" ] && echo "_dev" || echo "" )"

    # start tests and keep track of immediate and global return values
    local gret="0"
    local ret

    # test_util
    bash "${this_dir}/run_test" test_util
    ret="$?"
    [ "${gret}" = "0" ] && gret="${ret}"

    # test_columnar_util
    echo
    bash "${this_dir}/run_test" test_columnar_util "${cf_dir}/sandboxes/venv_columnar${dev}.sh"
    ret="$?"
    [ "${gret}" = "0" ] && gret="${ret}"

    # test_config_util
    echo
    bash "${this_dir}/run_test" test_config_util "${cf_dir}/sandboxes/venv_columnar${dev}.sh"
    ret="$?"
    [ "${gret}" = "0" ] && gret="${ret}"

    # test_hist_util
    echo
    bash "${this_dir}/run_test" test_hist_util "${cf_dir}/sandboxes/venv_columnar${dev}.sh"
    ret="$?"
    [ "${gret}" = "0" ] && gret="${ret}"

    # test_task_parameters
    echo
    bash "${this_dir}/run_test" test_task_parameters
    ret="$?"
    [ "${gret}" = "0" ] && gret="${ret}"

    # test_plotting
    echo
    bash "${this_dir}/run_test" test_plotting "${cf_dir}/sandboxes/venv_columnar${dev}.sh"
    ret="$?"
    [ "${gret}" = "0" ] && gret="${ret}"

    return "${gret}"
}
action "$@"
