# full list of jec sources in a fixed order that is used to assign consistent ids across configs
# (please add new sources at the bottom to preserve the order of existing ones)
names:
  - AbsoluteStat
  - AbsoluteScale
  - AbsoluteSample
  - AbsoluteFlavMap
  - AbsoluteMPFBias
  - Fragmentation
  - SinglePionECAL
  - SinglePionHCAL
  - FlavorQCD
  - TimePtEta
  - RelativeJEREC1
  - RelativeJEREC2
  - RelativeJERHF
  - RelativePtBB
  - RelativePtEC1
  - RelativePtEC2
  - RelativePtHF
  - RelativeBal
  - RelativeSample
  - RelativeFSR
  - RelativeStatFSR
  - RelativeStatEC
  - RelativeStatHF
  - PileUpDataMC
  - PileUpPtRef
  - PileUpPtBB
  - PileUpPtEC1
  - PileUpPtEC2
  - PileUpPtHF
  - PileUpMuZero
  - PileUpEnvelope
  - SubTotalPileUp
  - SubTotalRelative
  - SubTotalPt
  - SubTotalScale
  - SubTotalAbsolute
  - SubTotalMC
  - Total
  - TotalNoFlavor
  - TotalNoTime
  - TotalNoFlavorNoTime
  - FlavorZJet
  - FlavorPhotonJet
  - FlavorPureGluon
  - FlavorPureQuark
  - FlavorPureCharm
  - FlavorPureBottom
  - TimeRunA
  - TimeRunB
  - TimeRunC
  - TimeRunD
  - CorrelationGroupMPFInSitu
  - CorrelationGroupIntercalibration
  - CorrelationGroupbJES
  - CorrelationGroupFlavor
  - CorrelationGroupUncorrelated
