name: "Build images and test for multiple python versions"
on:
    push:
    workflow_dispatch:
        inputs:
            PYVERSION: 
              description: "Python version to be used for build"
              required: false
              type: choice
              default: "3.10"
              options:
                - "3.9"
                - "3.10"
                - "3.11"

jobs:
    do_all:
        strategy:
            fail-fast: false
            matrix: 
                # PYVERSION: ["3.9", "3.10"]
                PYVERSION: ["3.9", "3.10", "3.11"]
                FORCE_COMPILE_ENV: ["True"]
                
                    

        uses: ./.github/workflows/build_and_test_single.yaml
        secrets: inherit
        permissions:
            contents: read
            packages: write
        with:
            PYVERSION: ${{ matrix.PYVERSION }}
        name: "Build and test for Python ${{ matrix.PYVERSION }}"
